// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd1BKWw-nI1gYbTu65O8UjtwB0FY3T5bM',
    appId: '1:547819247679:web:927489a949e2f313c7c08a',
    messagingSenderId: '547819247679',
    projectId: 'minimalsocial-edcd8',
    authDomain: 'minimalsocial-edcd8.firebaseapp.com',
    storageBucket: 'minimalsocial-edcd8.appspot.com',
    measurementId: 'G-L0E61QTMW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpB7vD_VsRxYig0ezO7i0bt64rbNyx12M',
    appId: '1:547819247679:android:da54443261bf5d96c7c08a',
    messagingSenderId: '547819247679',
    projectId: 'minimalsocial-edcd8',
    storageBucket: 'minimalsocial-edcd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq34ci1CAgYawmsG3POKPWucSgVoMNWrM',
    appId: '1:547819247679:ios:8e4565806f86e87ac7c08a',
    messagingSenderId: '547819247679',
    projectId: 'minimalsocial-edcd8',
    storageBucket: 'minimalsocial-edcd8.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );
}
